
cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2

cache:
  directories:
  - $HOME/.m2
